### ISSUE TITLE
Unable to save requests when running in Flatpak

### ISSUE THREAD

**Issue by Vinibo** [bartkessels/GetIt#22]
I've been using Getit for a while now and I really enjoy using a GTK-native application for calling APIs but I had a consistent issue with saving requests.

Steps to reproduce:
1. Open the Flatpak runtime of GetIt
2. Execute a query in GetIt (For example: GET on 'https://jsonplaceholder.typicode.com/todos/1'
3. Save the current request in ~/Documents (Hamburger menu -> Save As) (In this case, let's name it test.req)

What's expected:
- I should find the file test.req at '~/Documents'
What's happening:
- the test.req file is not present.

I also notice a text in the bottom of the application that indicate that the file could be somewhere else (`File:/run/user1xxx/doc/xxxxxx/test.req`). But when I go there, there's no files.

Thanks for looking at this issue!

**Comment by XT-Martinez** [comment]
I can confirm this issue still exists.

**Comment by bartkessels** [comment]
Hi all, because of the rewrite to Qt this issue will be closed. In de Qt version a new flatpak application will be generated (hasn't been done yet) and perhaps this issue doesn't exist anymore. If you're both still interested in using the GTK version, this will still be available through the master branch but won't be actively maintained by me. Unless there's a PR which addresses this issue for the GTK version this feature won't get fixed. I'm really sorry and I hope you understand the reasoning.
