### ISSUE TITLE
Flathub package not installing

### ISSUE THREAD

**Issue by mijorus** [bartkessels/GetIt#58]
**Describe the bug**

**To Reproduce**
1. Run `flatpak install --user getit.flatpak`

**Expected behavior**
It should install

**Desktop (please complete the following information):**
 - OS: PopOS 22.04
 - Platform: x64

**Additional context**
The application requires a development version of `runtime/org.gnome.Platform`, while it should require one of the followings:

```
1) runtime/org.gnome.Platform/x86_64/3.24
   2) runtime/org.gnome.Platform/x86_64/3.26
   3) runtime/org.gnome.Platform/x86_64/3.28
   4) runtime/org.gnome.Platform/x86_64/3.30
   5) runtime/org.gnome.Platform/x86_64/3.32
   6) runtime/org.gnome.Platform/x86_64/3.34
   7) runtime/org.gnome.Platform/x86_64/3.36
   8) runtime/org.gnome.Platform/x86_64/3.38
   9) runtime/org.gnome.Platform/x86_64/40
  10) runtime/org.gnome.Platform/x86_64/41
  11) runtime/org.gnome.Platform/x86_64/42
  12) runtime/org.gnome.Platform/x86_64/43
```

**Comment by bartkessels** [comment]
Hi,

Thank you for the feedback. The current GetIt version from Flathub is based on GTK (Gnome), but because GetIt is being rewritten to Qt the current flatpak builds aren't working. This is a known issues which I'm working on right now.

Unfortunately this means that until the Qt version of GetIt can be released as a flatpak, the Flathub version (in Gnome) won't be updated due to lack of time/contributors.

Hopefully this won't discourage you from using GetIt when the rewrite is complete.
